config/routes.rb
Fbp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
    resources :entries
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :seasons do
    member do
      get 'foy'
      get 'agreements'
      put 'update_agreements'
    end
  end
  
  resources :weeks do
    member do
      get 'result'
      post 'result'
      get 'what_if'
      post 'what_if'
      get 'entry_list'
    end
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new', via: [:get, :post]
  match '/signin',  to: 'sessions#new', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help', via: [:get, :post]

  match '/about',    to: 'static_pages#about', via: [:get, :post]

  match '/contact',    to: 'static_pages#contact', via: [:get, :post]

end

app/models/week.rb
class Week < ActiveRecord::Base
  #attr_accessible :season_id, :week_num, :status
  validates :season_id, presence: true
  validates :week_num, presence: true, uniqueness: { scope: :season_id, message: "should happen once per year" }
  validates :status, inclusion: { in: %w(NOT_STARTED STARTED COMPLETE PUBLISHED), message: "%{value} is not NOT_STARTED STARTED COMPLETE or PUBLISHED" }


  belongs_to :season
  has_many :games, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_filter :signed_in_user

	def show
		Time.zone= "Pacific Time (US & Canada)"
		@user = current_user
		@week = Week.find(params[:id])
		@games = @week.games.sort { |a,b| a.start <=> b.start }
		@entries = @week.entries
		@entry = Entry.find_by_user_id_and_week_id(current_user.id, @week.id)
		if !@entry
			@entry = @week.entries.create(user_id: current_user.id, tiebreak: 0, status: "NEW"  )
		end
		@picks = @entry.picks
	end

	def result
		@week = Week.find(params[:id])
		view_context.update_scores @week
		@games, @players = view_context.get_games_and_players @week, :NEW
		@user = current_user
		if params[:commit] == 'Publish'
			@week.status = 'PUBLISHED'
			@week.comment = params[:comment]
			@week.save
			@players[0] && @players[0][:entry].winner = true
			@players[0] && @players[0][:entry].save
		end
	end

	def entry_list
		@week = Week.find(params[:id])
		entries = @week.entries
		@user = current_user
		@user_details = []
		User.all.each do |u|
			status = 'NO_ENTRY'
			entry = entries.find_by_user_id u.id
			entry && status = entry.status
			@user_details << {name: u.nickname, status: status}
		end
	end

	def what_if
		logger.info "===================================== W H A T    I F ================================"

		@week = Week.find(params[:id])
		view_context.update_scores @week

		action = :NEW
		action = :UPDATE if params[:commit] == "Update scenario"
		action = :PICKS if params[:commit] == "Use my picks"
		action = :BEST if params[:commit] == "Find my best shot"
		action = :RESET if params[:commit] == "Reset"
		action = :RESULTS if params[:commit] == "Use results"

		@games, @players, @outcomes = view_context.get_games_and_players @week, action, params

	    cutoff = @games[0].start
	    @early = (Time.now <= cutoff)

		@cpi = 0
		@players.each_with_index { |p,i| @cpi = i if p[:cu] }
		logger.debug "cpi: #{@cpi}"
		@user = current_user

	end

	# def foy
	# 	logger.info "===================================== F O Y ================================"

	# 	@week = Week.find(params[:id])
	# 	@status = view_context.update_scores

	# 	action = :NEW
	# 	action = :UPDATE if params[:commit] == "Update scenario"
	# 	action = :PICKS if params[:commit] == "Use my picks"
	# 	action = :BEST if params[:commit] == "Find my best shot"

	# 	@games, @players = view_context.get_games_and_players @week, action, params

	# 	@cpi = nil
	# 	@players.each_with_index { |p,i| @cpi = i if p[:cu] }
	# 	logger.debug "cpi: #{@cpi}"
	# 	@user = current_user

	# end
end

app/helpers/weeks_helper.rb
module WeeksHelper
	require 'json'
	require 'net/http'


	def update_scores(week)
		return if week.status == 'COMPLETE' or week.status == 'PUBLISHED'
		#host = 'www.nfl.com'
		host = '50.174.118.222'
		path = "/liveupdate/scorestrip/ss.json"

		#uri = URI('http://50.174.118.222:8000/cgi/nfl.py')
		uri = URI('http://www.nfl.com/liveupdate/scorestrip/ss.json')
		#ss = Net::HTTP.get(host, path)
		ss = Net::HTTP.get(uri)
		parsed = JSON.parse  ss
		# puts ss
		w = parsed["w"]
		year = parsed["y"]

		status = []
		s = Season.find_by_year year
		return status unless s
		status << "got season #{s.year}"

		#note: this might be a different week than we came in with
		week = s.weeks.find_by_week_num w
		return status unless week
		status << "got week #{week.week_num}"
		return if week.status == 'COMPLETE' or week.status == 'PUBLISHED'

		week_type = parsed["t"]
		return status unless week_type == "REG"
		status << "week type #{week_type}"

		#puts "results for ( status#{week_type}) Week #{w} #{year}"
		parsed["gms"].each do |game|
			status << ""
			away_team_code = game["v"]
			home_team_code = game["h"]
			away_team = game["vnn"]
			home_team = game["hnn"]
			disp_code = game["q"]
			disposition = "NOT STARTED" if disp_code == "P"
			disposition = "first quarter" if disp_code == "1"
			disposition = "second quarter" if disp_code == "2"
			disposition = "third quarter" if disp_code == "3"
			disposition = "fourth quarter" if disp_code == "4"
			disposition = "overtime" if disp_code == "5"
			disposition = "Final" if disp_code == "F"
			disposition = "Final overtime" if disp_code == "FO"


			home_score = game["hs"]
			away_score = game["vs"]

			ht = Team.find_by_code home_team_code
			return status unless ht

			status << "home team: #{ht.nickname}"

			g = week.games.find_by_home_team_id ht.id
			return status unless g

			g.status = "NOT STARTED" if disp_code == "P"
			g.status = "STARTED" if disp_code == "1"
			g.status = "STARTED" if disp_code == "2"
			g.status = "STARTED" if disp_code == "3"
			g.status = "STARTED" if disp_code == "4"
			g.status = "STARTED" if disp_code == "5"
			g.status = "COMPLETE" if disp_code == "F"
			g.status = "COMPLETE" if disp_code == "FO"
			status << "game status: #{g.status}"


			g.home_points = home_score.to_i
			g.away_points = away_score.to_i
			status << "home score: #{g.home_points}, away score: #{g.away_points}"

			g.save
			n = false # seen not started game
			s = false # seen started game
			c = false # seen complete game
			week.games.each do |g|
				n = true if g.status == 'NOT_STARTED'
				s = true if g.status == 'STARTED'
				c = true if g.status == 'COMPLETE'
			end

			if c && !s && !n
				week.status = 'COMPLETE'
			elsif s
				week.status = 'STARTED'
			else
				week.status = 'NOT_STARTED'
			end
		
			week.save
			
			#puts "#{away_team} #{away_score} at  #{home_team} #{home_score}   (#{disposition})"
		end

		status
	end


    Player = Struct.new(:name, :points, :user, :picks, :tb, :cu, :sort_points)


    def get_games_and_players(week, action, params = nil)
	  entries = week.entries

	  games = week.games.sort_by { |g| "#{g.start.strftime '%Y-%m-%d_%H:%M'}-#{g.home_team.nickname}" }
	  tb_game = nil

	  cue = entries.first
	  entries.each do |e|
	  	if e.user_id == current_user.id
	  		cue = e
	  		break
	  	end
	  end

	  outcomes = []
	  games.each do |g|
	  	logger.debug "get_games_and_players #{g.away_team.nickname} at #{g.home_team.nickname} (#{g.away_team.code} at #{g.home_team.code})"
	  	g.home_points = 0 if g.home_points == nil
	  	g.away_points = 0 if g.away_points == nil
	  	if g.tiebreak 
	  		logger.debug "setting as tiebreak game"
	  		tb_game = g
	  	end

  		cu_pick = nil
  		cue.picks.each do |cup|
  			if cup.game.id == g.id
  				cu_pick = cup
  				break
  			end
  		end

  		logger.debug "get_games_and_players        action: #{action}"
  		case action
  		when :RESET
  			outcome = 'NR'
  		when :BEST
  			outcome = 'NR'
  		when :UPDATE
  			outcome = params["game_#{g.id}"]
  		when :PICKS
  			outcome = 'NR'
  			outcome = cu_pick.pick if cu_pick
  		when :RESULTS, :NEW
  			if g.status == 'NOT_STARTED'
  				outcome = 'NR'
	  			outcome = params["game_#{g.id}"] if params && params["game_#{g.id}"]
  			else
	  			outcome = 'HOME' if g.home_points > g.away_points
	  			outcome = 'AWAY' if g.away_points > g.home_points
	  			outcome = 'TIE' if g.away_points == g.home_points
  			end
  		else
  			outcome = 'NR'
  		end

  		home_color = away_color = "green" #default
  		case outcome
  		when 'NR'
  		when 'TIE'
  			home_color = away_color = "red"
  		when 'HOME'
  			home_color = "red"
  			away_color = "black"
  		when 'AWAY'
  			home_color = "black"
  			away_color = "red"
  		end
  		outcomes << {game: g, home_color: home_color, away_color: away_color, outcome: outcome}
	  end

	  tb_game_points = tb_game ? tb_game.home_points + tb_game.away_points : 0

	  # build an array of player information, so we can later sort it by calculatd total points
	  players = []
	  entries.each do |e|
	  	next unless e.picks.size == week.games.size && e.tiebreak && e.tiebreak > 0
	  	player = { #Player.new( e.user.nickname, 0, e.user, [], e.tiebreak, e.user.id == current_user.id)
	  		name: e.user.nickname,
	  		points: 0,
	  		user: e.user,
	  		picks: [],
	  		choices: [],
	  		colors: [],
	  		dpoints: [],
	  		tb: e.tiebreak,
	  		cu: e.user.id == current_user.id,
	  		sort_points: 0,
	  		pos: '',
	  		entry: e
	  		}

	  	logger.debug "get_games_and_players player: #{player[:name]} player tb: #{player[:tb]} entry tb: #{e.tiebreak}, Current user: #{player[:cu]}"

	  	# build the player picks array and calculate total points for the player
	  	# note it is important that the player picks are ordered the same way as the
	  	# games, since we'll be displaying them with no further reference to the games

	  	#games.each do |g|
	  	outcomes.each do |o|
	  		g = o[:game]
	  		outcome = o[:outcome]
	  		logger.debug "get_games_and_players      game: #{g.away_team.code} at #{g.home_team.code}"
	  		pick = nil
	  		e.picks.each do |entry_pick|
	  			if entry_pick.game.id == g.id
	  				pick = entry_pick
	  				break
	  			end
	  		end

	  		dpoints = 0
	  		color = "blue"
	  		logger.debug "get_games_and_players        outcome: #{outcome}"
	  		case outcome
	  		when 'NR'
	  			dpoints = pick.points
				color = "green"
	  		when 'TIE'
	  			dpoints = pick.points/2.0
				player[:points] += dpoints
				color = "red"
			else
				if pick.pick == outcome
		  			dpoints = pick.points.to_i
					player[:points] += dpoints
  					color = "red"
				else
		  			dpoints = pick.points
  					color = "black"
  				end
	  		end

	  		#player[:picks] << pick
	  		player[:colors] << color
	  		player[:dpoints] << dpoints
	  	end
	  	logger.debug "choices: #{player[:choices]}"
	  	player[:sort_points] = player[:points]
	  	# add an increment to diffentiate by tiebreak
	  	player[:sort_points] += (1000 -((tb_game_points - player[:tb]).abs)/10000.0)
	  	# add an even smaller increment to differentiate low tiebreak vs high (low wins)
	  	player[:sort_points] += 0.00001 if player[:tb] > tb_game_points 
	  	player[:sort_points] += 0.00002 if player[:tb] < tb_game_points 

	  	players << player
	  end

	  players.sort! { |a,b|  b[:sort_points] <=> a[:sort_points] }

      prev_sort_points = -1
      prev_pos = 0
      results = []
      players.each_with_index do |player,i|
        if player[:sort_points] == prev_sort_points
          player[:pos] = prev_pos
        else
          player[:pos] = i + 1
        end

        prev_sort_points = player[:sort_points]
        prev_pos = player[:pos]
 	  end

	  [games, players, outcomes]  
    end

    def gen_foy_data
    	Week.all.sort_by_week_num do |w|
    		logger.debug "gen_foy_data #{w.week_num}"
    	end
    end
end

app/views/weeks/_week.html.erb
<li>
  <%= link_to "Week #{week.week_num}", week %>
  (must enter by: <%= @cutoff[week.week_num].strftime("%A, %B %e  %l:%M %p") %>)
</li>

app/views/weeks/entry_list.html.erb
<% provide(:year, "#{@week.season.year}") %>
<h1> FBP<sub>hq</sub> Entry Summary for Week <%= @week.week_num %></h1>
<!--h2> SUBJECT TO CONFIRMATION </h2-->
<% if @user.admin %>
		<div class="span8 offset1">
			<p style="color: red">
			You are seeing this list because you are an administrator.
			<p>
			<ul>
				<% @user_details.each do |ud|
					color = 'white'
					case ud[:status]
						when 'NO_ENTRY'
							color = 'red'
						when 'NEW'
							color = 'red'
						when 'INCOMPLETE'
							color = 'red'
						when 'COMPLETE'
							color = 'yellow'
						when 'LOCKED'
							color = 'lightgreen'
					end %>
					<li style="background: <%= color %>"><%= ud[:name] %> <%= ud[:status] %></li>
				<% end %>
			</ul>
		</div>
<% else %>
			<p style="color: red">
			This view is available only for administrators.
<% end %>

<div class="span10 offset2">
	<p>
	<%= link_to "Week #{@week.week_num} Summary",   week_path(@week) %>
    <p>
    <%= link_to "FOY", foy_season_path(@week.season) %>
</div>

app/views/weeks/result.html.erb
<% provide(:year, "#{@week.season.year}") %>
<h1> FBP<sub>hq</sub> Results Week <%= @week.week_num %></h1>
<!--h2> SUBJECT TO CONFIRMATION </h2-->
<% if  @week.status == 'COMPLETE' && @user.admin %>
		<div class="span8 offset1">
			<p style="color: red">
			The results below are not generally viewable. As the administrator you decide when the results
			are to be published. Note that once published, results cannot be "unpublished".

			Press the "Publish" button only when you are sure the results are correct.
			<p>
			<%= form_tag do %>
				<p>
				<%= label_tag :comment, "Comment:" %>
				<%= text_field_tag :comment %>			
        		<%= submit_tag("Publish", class: "btn btn-large btn-primary") %>
			<% end %>
		</div>
<% end %>

<% if @week.status == 'PUBLISHED' || (@week.status == 'COMPLETE' && @user.admin) %>
	<div class="span6 offset1" style="background: khaki; border-radius: 15px">
	<div class="span4 offset1" style="background: khaki">
		<%= @week.comment %>
		<table>
			<tr><td><p></td></tr>
			<% @players.each do |p| %>
				<tr>
					<td> <%= p[:pos] %> </td>
					<td> ..... </td>
					<td> <%= p[:name] %> </td>
					<td> ..... </td>
					<td> <%= p[:points] %> </td>
				</tr>
			<% end %>
			<td><p></td>
		</table>
	</div>
	</div>
<% else %>
	Results for this week are not yet available.
<% end %>

<div class="span10 offset2">
	<p>
	<%= link_to "Week #{@week.week_num} Summary",   week_path(@week) %>
    <p>
    <%= link_to "FOY", foy_season_path(@week.season) %>
</div>

app/views/weeks/show.html.erb
<% provide(:title, "#{@week.season.year} week #{@week.week_num}") %>
<% provide(:year, "#{@week.season.year}") %>
<div class="row">
  <div class="span2">
   <ul class="week_week_list">
      <% @week.season.weeks.sort_by { |a| a.week_num }.each do |w| %>
        <li>
              <%= link_to "Week #{w.week_num}",   week_path(w) %>
        </li>
      <% end %>
    </ul>
  </div> 
    <ul>
  <div class="span6 offset1">
    <% if @games.any? %>
      <h3>Week <%= @week.week_num %> Games (<%= @games.count %>)</h3>
      <ol class="games">
        <%= render @games %>
      </ol>
    <% end %>
  </div>
  </ul>
</div>
<div class="row">
  <div class="span6 offset4">
    <%= link_to "Entry...", user_entry_path(@user, @entry), class: "btn btn-primary" %>
    <%= link_to "What if", what_if_week_path, class: "btn btn-primary" %>
    <%= link_to "Results", result_week_path, class: "btn btn-primary" %>
    <% if @user.admin %>
      <%= link_to "Entries Summary", entry_list_week_path, class: "btn btn-primary" %>
    <% end %>
        <p/>
    <%= link_to "FOY", foy_season_path(@week.season) %>
    <p><%= link_to "Season", season_path(@week.season) %></p>
  </div>
</div>

app/views/weeks/what_if.html.erb
<% provide(:year, "#{@week.season.year}") %>
<h1> Week <%= @week.week_num %> What If... </h1>

<p>	Points for correct picks are in red, incorrect picks in black, and points that don't yet count either way are in green.  your total is in blue. The game headers have the winning team in red. Team codes are underlined for completed games


<% if @early %>
	<h2 style="color: red">Games for this week have not yet started</h2>
<% else %>
	<%= form_tag do %>
	<table>
		<tr><td><p></td></tr>
		<tr>
				<td> </td>
				<td> </td>
				<td> </td>
				<td> </td>
				<td> </td>
				<td> </td>
				<% @outcomes.each_with_index do |o, i|
					g = o[:game]
					outcome = o[:outcome]
					home_color = o[:home_color]
					away_color = o[:away_color]

					ul1 = ""
					ul2 = ""
					if g.status == 'COMPLETE'
						ul1 = "<u>"
						ul2 = "</u>"
					end
				%>

					<td>
						<%= radio_button_tag "game_#{g.id}", 'NR', outcome == 'NR' %><b style="color: black"><sub>NR</sub></b><p>
						<%= radio_button_tag "game_#{g.id}", 'TIE', outcome == 'TIE' %><b style="color: black"><sub>TIE</sub></b><p>
						<%= radio_button_tag "game_#{g.id}", 'AWAY', outcome == 'AWAY' %><b style="color: <%= away_color%>"><sub><%= (ul1 + g.away_team.code + ul2).html_safe %></sub></b><p>
						<%= radio_button_tag "game_#{g.id}", 'HOME', outcome == 'HOME' %><b style="color: <%= home_color%>"><sub><%= (ul1 + g.home_team.code + ul2).html_safe %></sub></b>
					</td>
			<% end %>
		</tr>
		<% @players.each_with_index do |p, i|
			row_colors = ["cornsilk", "gainsboro"]
			row_color =  row_colors[i%2]
		%>
			<tr>
				<td style="background: <%= row_color %>"> <%= p[:pos] %> </td>
				<td style="background: <%= row_color %>"> .... </td>
				<td style="background: <%= row_color %>"> <%= p[:name] %> </td>
				<td style="color: gray; background: <%= row_color %>"> <b><%= p[:tb] %></b> </td>
				<td style="background: <%= row_color %>"> ... </td>
				<td style="color: blue; background: <%= row_color %>"> <b><%= p[:points] %></b> </td>
				<% p[:dpoints].each_with_index do |ch,j| %>
					<td style="color: <%= p[:colors][j]%>; background: <%= row_color %>"> <%= p[:dpoints][j] %> </td>
				<% end %>
			</tr>
		<% end %>
		<tr><td><p></td></tr>
	</table>
	        <%= submit_tag("Update scenario", class: "btn btn-large btn-primary") %>
	        <%= submit_tag("Use my picks", class: "btn btn-large btn-primary") %>
	        <%= submit_tag("Use results", class: "btn btn-large btn-primary") %>
	        <%= submit_tag("Reset", class: "btn btn-large btn-primary") %>
	        <!--%= submit_tag("Find my best shot", class: "btn btn-large btn-primary") %-->
	<% end %>
<% end %>

	<div class="span10 offset2">
	<p>
	<%= link_to "Week #{@week.week_num} Summary",   week_path(@week) %>
</div>

app/views/weeks/what_if.html_save.erb
<h1> Week <%= @week.week_num %> What If... </h1>

<p> Results below should be accurate, but need to be checked. Please check your
	own results.
<p>	Points for correct picks are in red, incorrect picks in black, and points that don't yet count either way are in green.  your total is in blue. The game headers have the winning team in red.

<p> Please email any discrepancies to fbphq@yahoo.com
	 <!-- Points in the body of the table are underlined for away team picks. -->

<p>Thanks for your patience while we get this figured out</p>


<%
	cp = @players[@cpi]
	chs = cp[:choices]
%>
<%= form_tag do %>
<table>
	<tr><td><p></td></tr>
	<tr>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
			<% @games.each_with_index do |g, i|
				cp_pick = chs[i]
				home_color = "green"
				away_color = "green"
				unless g.status == 'NOT_STARTED'
					(home_color = "red"; away_color = "black") if g.home_points >= g.away_points
					(home_color = "gray"; away_color = "red") if g.away_points >= g.home_points
				end
			%>
				<td>
					<%= radio_button_tag "game_#{g.id}", 'NR', cp_pick == 'NR' %><b style="color: black"><sub>NR</sub></b><p>
					<%= radio_button_tag "game_#{g.id}", 'TIE', cp_pick == 'TIE' %><b style="color: black"><sub>TIE</sub></b><p>
					<%= radio_button_tag "game_#{g.id}", 'AWAY', cp_pick == 'AWAY' %><b style="color: <%= away_color%>"><sub><%= g.away_team.code %></sub></b><p>
					<%= radio_button_tag "game_#{g.id}", 'HOME', cp_pick == 'HOME' %><b style="color: <%= home_color%>"><sub><%= g.home_team.code %></sub></b>
				</td>
		<% end %>
	</tr>
	<% @players.each_with_index do |p, i|
		row_colors = ["cornsilk", "gainsboro"]
		row_color =  row_colors[i%2]
	%>
		<tr>
			<td style="background: <%= row_color %>"> <%= p[:pos] %> </td>
			<td style="background: <%= row_color %>"> .... </td>
			<td style="background: <%= row_color %>"> <%= p[:name] %> </td>
			<td style="color: gray; background: <%= row_color %>"> <b><%= p[:tb] %></b> </td>
			<td style="background: <%= row_color %>"> ... </td>
			<td style="color: blue; background: <%= row_color %>"> <b><%= p[:points] %></b> </td>
			<% p[:choices].each_with_index do |ch,j| %>
				<td style="color: <%= p[:colors][j]%>; background: <%= row_color %>"> <%= p[:dpoints][j] %> </td>
			<% end %>
		</tr>
	<% end %>
	<tr><td><p></td></tr>
</table>
        <%= submit_tag("Update scenario", class: "btn btn-large btn-primary") %>
        <%= submit_tag("Use my picks", class: "btn btn-large btn-primary") %>
        <%= submit_tag("Use results", class: "btn btn-large btn-primary") %>
        <!--%= submit_tag("Find my best shot", class: "btn btn-large btn-primary") %-->
<% end %>

<!-- div class="span10 offset1" style="background: khaki; border-radius: 15px">
<div class="span8 offset1" style="background: khaki">
	<%= form_tag do %>
		<table>
			<% @games.each do |game| %>
			<tr>
				<td "padding=20">
					<%= radio_button_tag "game_#{game.id}", 'away' %><p>
				</td>
				<td>
					<%= label_tag "game_#{game.id}_away", game.away_team.display_name %>
				</td>
				<td>
					___ at ____
				</td>
				<td>
					<%= radio_button_tag "game_#{game.id}", 'home', true %><p>
				</td>
				<td>
					<%= label_tag "game_#{game.id}_home", game.home_team.display_name %>
				</td>
				<td>
					<%= radio_button_tag "game_#{game.id}", 'tie' %><p>
				</td>
				<td>
					<%= label_tag "game_#{game.id}_home", "tie" %>
				</td>
				<td>
					_______
				</td>
				<td>
					COMPLETED
				</td>
			</tr>
			<% end %>
		</table>
        <%= submit_tag("Update scenario", class: "btn btn-large btn-primary") %>
        <%= submit_tag("Use my picks", class: "btn btn-large btn-primary") %>
        <%= submit_tag("Find my best shot", class: "btn btn-large btn-primary") %>
	<% end %>
</div>
</div -->