config/routes.rb
Fbp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
    resources :entries
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :seasons do
    member do
      get 'foy'
      get 'agreements'
      put 'update_agreements'
    end
  end
  
  resources :weeks do
    member do
      get 'result'
      post 'result'
      get 'what_if'
      post 'what_if'
      get 'entry_list'
    end
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new', via: [:get, :post]
  match '/signin',  to: 'sessions#new', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help', via: [:get, :post]

  match '/about',    to: 'static_pages#about', via: [:get, :post]

  match '/contact',    to: 'static_pages#contact', via: [:get, :post]

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  #attr_accessible :status, :tiebreak, :user_id, :week_id
  attr :picks
  validates :status, presence: true, inclusion: { in: %w(NEW INCOMPLETE COMPLETE LOCKED), message: "%{value} is not NEW, INCOMPLETE, COMPLETE or LOCKED" }
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :week
  #has_many :picks, dependent: :destroy

  before_save do
    self.details = create_json
  end

  class P
    attr_accessor :points, :pick, :game
    def initialize game, i
      @points = i
      @pick = "NONE"
      @game = game
    end
  end

  def create_json
    return "{}" if !@picks
    temp = {}
    @picks.each do |p|
      t = 'NONE'
      t = p.game.home_team.code if p.pick == "HOME"
      t = p.game.away_team.code if p.pick == "AWAY"
      temp[p.points] = t
    end
    JSON.generate temp
  end

  # todo: make these private
  def create_picks
    @picks = []
    week.games.each_with_index do |g, i|
      @picks.append P.new g, i+1
    end
    if details
      (JSON.parse details).each do |points,code|
        # team = Team.find_by_code code
        # game = Game.find_by_home_team_id_and_week_id team.id, week.id
        # game = Game.find_by_away_team_id_and_week_id team.id, week.id if !game
        game = Game.by_team_code_and_week code, week
        if game
          @picks.each do |p|
            if p.game.id == game.id
              p.points = points.to_i
              p.pick = "HOME" if code == game.home_team.code
              p.pick = "AWAY" if code == game.away_team.code 
            end
          end
        end
      end
    end
    @picks
  end

  def picks
    #return "picks exist" if @picks
    @picks ? @picks : create_picks
  end

  def get_points
    return points if points
    logger.info "getting points for entry, user: #{user.name}, week: #{week.week_num}, points: #{points}}"
  	points = 0
  	picks.each do |p|
  		g = p.game
  		next unless g.status == 'COMPLETE'
  		hp = g.home_points ? g.home_points : 0
  		ap = g.away_points ? g.away_points : 0
  		case p.pick
  		when 'HOME'
  			points += p.points if hp > ap
  			points += p.points/2.0 if hp == ap
  		when 'AWAY'
  			points += p.points if ap > hp
  			points += p.points/2.0 if ap == hp
  		end
  	end

    save
  	points
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user, only: [:edit, :update, :destroy]

  def new
  end

  def show
    setup
    @picks = @picks.sort { |a, b| a.points <=> b.points }
    ensure_entries
  end

  def edit
    @entry = Entry.find(params[:id])
    @user = current_user
    @week = @entry.week
    @games = @week.games
    @total_games = @games.size
    @total_points = (1..@total_games).inject { |a,b| a + b }
    Time.zone= "Pacific Time (US & Canada)"

    @picks = @entry.picks.sort { |a, b| a.game.start == b.game.start ? a.game.home_team.name <=> b.game.home_team.name : a.game.start <=> b.game.start }
  end
  
  def update
    flash.clear
    Time.zone= "Pacific Time (US & Canada)"
    @entry = Entry.find(params[:id])
    @week = @entry.week
    @games = @week.games.sort { |a,b| a <=> b }
    @total_games = @games.size
    @total_points = (1..@total_games).inject { |a,b| a + b }
    n = @games.size

    cutoff = @games[0].start
    if Time.now > cutoff
      @picks = @entry.picks.sort { |a, b| a.game.start == b.game.start ? a.game.home_team.name <=> b.game.home_team.name : a.game.start <=> b.game.start }
      flash.now[:alert] = " Sorry, cutoff time for week #{@week.week_num} has passed"
      ensure_entries
      render 'show' and return
    end

    @user = current_user

    usage = Array.new(n+1, 0)
    problems = []

    #@picks = @entry.picks.sort { |a, b| a.game.start <=> b.game.start }
    @entry.picks.each do |pick|
      home_points = params[pick.game.home_team.code].to_i
      away_points = params[pick.game.away_team.code].to_i
      if home_points > 0 && home_points <= n && away_points == 0
          pick.points = home_points
          usage[home_points] += 1
          pick.pick = "HOME"
      elsif away_points > 0 && away_points <= n && home_points == 0
          pick.points = away_points
          usage[away_points] += 1
          pick.pick = "AWAY"
      else
        pick.points = 0
        pick.pick = 'NONE'
        problems << "No valid pick for #{pick.game.away_team.name} at #{pick.game.home_team.name}"
      end
    end

    tb = params['tiebreak']
    if tb.strip.length == 0 || tb.to_i < 0
      problems << 'Tiebreak is missing'
      @entry.tiebreak = nil
    else
      @entry.tiebreak = tb.to_i
      logger.debug "Setting tiebreak to #{@entry.tiebreak}"
    end

    @entry.save

    problems.each do |p|
      @entry.errors[:base] << p
    end

    (1..n).each do |x|
      if usage[x] == 0
        @entry.errors[:base] << "Number #{x} not used"
      elsif usage[x] == 2
        @entry.errors[:base] << "Number #{x} used twice"
      elsif usage[x] > 2
        @entry.errors[:base] << "Number #{x} used #{usage[x]} times"
      end
    end

    if @entry.errors.any?
      render 'edit'
    else
      @entry.status = 'COMPLETE'
      @entry.save
      flash.now[:success] = "Congratulations! Your week #{@week.week_num} picks are good!"
      @picks = @entry.picks.sort { |a, b| a.points <=> b.points }
      EntryMailer.entry_email(@entry).deliver
      ensure_entries
      render 'show'
    end

  end

  def create
  end

  def destroy
    @entry.destroy
    redirect_to root_url
  end

  private
    def ensure_entries
      weeks = @entry.week.season.weeks.sort { |a,b| a <=> b }
      @entries = []
      weeks.each do |w|
        e = Entry.find_by_user_id_and_week_id(current_user.id, w.id)
        if !e
          e = w.entries.create(user_id: current_user.id, tiebreak: 0, status: "NEW"  )
          e.save
        end
        @entries.append e
      end

      @entries = @entries.sort {|a,b| a.week.week_num <=> b.week.week_num}

    end

    def setup
      @entry = Entry.find(params[:id])
      @user = current_user
      @week = @entry.week
      @games = @week.games
      Time.zone= "Pacific Time (US & Canada)"

      @picks = @entry.picks.sort { |a, b| a.game.start <=> b.game.start }
    end

    def correct_user
     entry = Entry.find(params[:id])
     if entry.user_id != current_user.id
      flash[:error] = "You cannot work with other peoples' entries"
      redirect_to root_url
     end
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
	def cani
		"yes"
	end
end

app/views/entries/_one_game.html.erb
 <div class="row">
  <div class="span6" style="background: goldenrod">
  	<div class="row">
		<div class="span2" style="text-align: right"><%= label_tag(:q, game.away_team.city) %></div>
		<div class="span1"><%= text_field_tag 'away', '42', size: 3 %></div>
		<div class="span1"><%= text_field_tag 'home', '42', size: 3 %></div>
		<div class="span2"><%= label_tag(:q, game.home_team.city) %></div>
	</div>
  </div>
</div>

app/views/entries/_one_pick.html.erb
<%
	@gdate = pick.game.start.in_time_zone.strftime("%A, %B %e")
	@gtime = pick.game.start.in_time_zone.strftime("%l:%M %p")
%>

<% if @gdate != @pdate %>
  <div class="row">
    <div class="span6" style="background: khaki">
      <p/>
    </div>
    <div class="span6" style="background: gold; text-align: center">
      <%= @gdate %>
    </div>
    <div class="span6" style="background: gold; text-align: left">
      <%= @gtime %>
    </div>
  </div>
<% elsif @gtime != @ptime %>
  <div class="row">
    <div class="span6" style="background: gold; text-align: left">
      <%= @gtime %>
    </div>
  </div>
<% end %>
<% if pick.game.tiebreak %>
  <div class="row">
    <div class="span6" style="background: gold; text-align: left">
      Tiebreak Game
    </div>
  </div>
<% end %>

<%
	@pdate = @gdate
	@ptime = @gtime
%>



<div class="row">
  <div class="span6" style="background: gold">
  	<div class="row">
		<div class="span2" style="text-align: right"><%= label_tag(:q, pick.game.away_team.display_name) %></div>
		<div class="span1"><%= text_field_tag pick.game.away_team.code, pick.pick == 'AWAY'? pick.points : '', size: 3 %></div>
		<div class="span1"><%= text_field_tag pick.game.home_team.code, pick.pick == 'HOME'? pick.points : '', size: 3 %></div>
		<div class="span2"><%= label_tag(:q, pick.game.home_team.display_name) %></div>
	</div>
  </div>
</div>

app/views/entries/edit.html.erb
<% provide(:title, 'Entry') %>
<% provide(:year, "#{@week.season.year}") %>
<h1>Entry for week <%= @week.week_num%></h1>

<div class="row">
  <div class="span10 offset1" style="background: khaki; border-radius: 15px">
    <p/>
  <div class="span6 offset2">
    <%= render 'shared/error_messages', object: @entry %>
    <h2>Total games: <%= @total_games %>, Possible points: <%= @total_points %></h2>
    <%= form_tag("/users/#{@user.id}/entries/#{@entry.id}", action: "update", method: "put", xyz: 'just') do%>
      <% @pdate = "xxx" %>      
      <% @ptime = "xxx" %>      
      <%= render partial: "one_pick", collection: @picks, as: :pick %>
      <div class="span6" style="background: khaki">
        <p/>
      </div>
      <div class="row">
        <div class="span2">
          <%= label_tag(:q, "Tiebreak:", style: 'text-align: right') %>
        </div>
        <div class="span1">
          <%= text_field_tag(:tiebreak, @entry.tiebreak.to_i > 0? @entry.tiebreak : '') %>
        </div>
        <div class="span3">
        </div>
      </div>
      <div class="row">
        <div class="span1 offset4">
          <%= submit_tag("Submit Entry", class: "btn btn-large btn-primary") %>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/entries/new.html.erb
<% provide(:title, 'Entries') %>
<h1>New Entry</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :year %>
      <%= f.text_field :season %>

      <%= f.label :week %>
      <%= f.text_field :week %>

      <%= f.label :tiebreak %>
      <%= f.text_field :tiebreak %>

      <%= for(@game_list) do |g| %>
      <%= end %>

      <%= f.submit "Submit Entry", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/entries/show.html.erb
<% provide(:title, 'Valid Entry') %>
<% provide(:year, "#{@week.season.year}") %>
<h1>Entry for week <%= @week.week_num%></h1>




<div class="row">
	<div class="span12">
		<div class="row-fluid">
			<div class="span2">
				<ul class="entry_weeks_list">
					<% @entries.each do |e| %>
						<li>
				      		<%= link_to "Entry for week: #{e.week.week_num}",  user_entry_path(current_user,e) %>
						</li>
					<% end %>
				</ul>
			</div> 
			<div class="span10 entrylist">
				<div class="row">
					<div class="span7 offset2"
					    <ul class="picklist">
					      	<% action = false %>
					      	<% @picks.each do |pick| %>
					      		<% if pick.pick != 'NONE' %>
						      		<li class="pickline"><%= pick.points %> on
							      		<%= pick.pick == 'HOME'? pick.game.home_team.display_name : pick.game.away_team.display_name %>
							      		to beat 
							      		<%= pick.pick == 'HOME'? pick.game.away_team.display_name : pick.game.home_team.display_name %>
							      		<%= pick.pick == 'HOME'? " at home" : "away" %>
							      		<% if pick.game.tiebreak %> (tiebreak game) <% end %>
						      		</li>
						      		<% action = true %>
					      		<% end %>	
					      	<% end %>
					    </ul>
					</div>
				</div>

				<div class="row">
			      	<div class="span4 offset2">
			        	<% if @entry.tiebreak.to_i > 0 %>
			        		Tiebreak: <%= @entry.tiebreak.to_i %>
			    		<% action = true; end %>
			    		<% if !action %>
			    			(entry has not been started)
			    		<% end %>
			      	</div>
				</div>

				<div class="row">
				  	<div class="row">
				      <div class="span10 offset5">
				      	<%= link_to "Edit Entry",   edit_user_entry_path %>
				      </div>
				  	</div>
				  	<div class="row">
				      <div class="span10 offset5">
				      	<%= link_to "Week #{@week.week_num} Summary",   week_path(@week) %>
				      </div>
				  	</div>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/entries/update.html.erb
<h1>Update successful</h1>
<%= @home_points %>  <%= @away_points %>